sudo: required

services:
  - docker

script:
  - cd base_image_sensu; docker build -t jonathanbeber/sensu:latest .
  
after_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push jonathanbeber/sensu:latest

branches:
  only:
  - master
