version: '3'
services:
  database:
    image: mysql:5.6
    volumes:
      - db-persistence:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD="${DATABASE_PASSWORD:-defaultdbpassword}"
volumes:
  db-persistence:
