version: '3'
services:
  database:
    image: mysql:5.6
    volumes:
      - db-persistence:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-defaultdbpassword}
  config-database:
    build: config-database/.
    environment:
      - APPLICATION_NAME=${APPLICATION_NAME:-devops-challenge}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-defaultdbpassword}
      - APPLICATION_PASSWORD=${APPLICATION_PASSWORD:-defaultapppassword}
    links:
      - database
  web-app:
    build:
      context: web-app/.
      args:
        - APPLICATION_NAME=${APPLICATION_NAME:-devops-challenge}
        - APPLICATION_PASSWORD=${APPLICATION_PASSWORD:-defaultapppassword}
    image: web-app
    ports:
      - 8000:80
    links:
      - database
    depends_on:
      - config-database
volumes:
  db-persistence:
