version: '3'
services:
  database:
    image: mysql:5.6
    volumes:
      - db-persistence:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-defaultdbpassword}
  config-database:
    build: config-database/.
    environment:
      - APPLICATION_NAME=${APPLICATION_NAME:-devops-challenge}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-defaultdbpassword}
      - APPLICATION_PASSWORD=${APPLICATION_PASSWORD:-defaultapppassword}
volumes:
  db-persistence:
