- hosts: localhost
  vars:
    application_name: "{{ lookup('env','APPLICATION_NAME') }}"
    application_password: "{{ lookup('env','APPLICATION_PASSWORD') }}"
    database_password: "{{ lookup('env','DATABASE_PASSWORD') }}"
    database_user: "root"
  tasks:
  - name: wait for mysql
    wait_for:
      host: database
      port: 3306
      delay: 10
  - name: create application's database
    mysql_db:
      name: "{{ application_name }}"
      state: present
      login_host: "database"
      login_user: "{{ database_user }}"
      login_password: "{{ database_password }}"
  - name: create application's user
    mysql_user:
      name: "{{ application_name }}"
      password: "{{ application_password }}"
      priv: '{{ application_name }}.*:ALL'
      state: present
      login_host: "database"
      login_user: "{{ database_user }}"
      login_password: "{{ database_password }}"
