- hosts: localhost
  vars:
    application_name: "{{ lookup('env','APPLICATION_NAME') }}"
    application_password: "{{ lookup('env','APPLICATION_PASSWORD') }}"
    database_password: "{{ lookup('env','DATABASE_PASSWORD') }}"
    monitor_user: "{{ lookup('env','DATABASE_MONITOR_USER') }}"
    monitor_user_password: "{{ lookup('env','DATABASE_MONITOR_USER_PASSWORD') }}"
  tasks:
  - name: wait for mysql
    wait_for:
      host: database
      port: 3306
      delay: 10
  - name: create application's database
    mysql_db:
      name: "{{ application_name }}"
      state: present
      login_host: "database"
      login_user: "root"
      login_password: "{{ database_password }}"
  - name: create application's user
    mysql_user:
      name: "{{ application_name }}"
      password: "{{ application_password }}"
      priv: '{{ application_name }}.*:ALL'
      host: '%'
      state: present
      login_host: "database"
      login_user: "root"
      login_password: "{{ database_password }}"
  - name: Import migrate.sql
    mysql_db:
      state: import
      name: "{{ application_name }}"
      target: /ansible/migrate.sql
      login_host: "database"
      login_user: "root"
      login_password: "{{ database_password }}"
  - name: create sensu's user
    mysql_user:
      name: "{{ monitor_user }}"
      password: "{{ monitor_user_password }}"
      priv: '*.*:SELECT,SHOW VIEW,PROCESS,REPLICATION CLIENT'
      host: '%'
      state: present
      login_host: "database"
      login_user: "root"
      login_password: "{{ database_password }}"
